### ISSUE TITLE
question on scores

### ISSUE THREAD

**Issue by fawazsammani** [maximek3/e-ViL#2]
Dear @maximek3 
Thanks for your work.

I have a question on your reimplementation of the methods you provide in Table 11 for VQA-X. There is a difference in the scores between Table 11 and Table 8. Why ones are correct and why is this increase? For example in in Table you report the score for CIDER for FME as 77.9, but in Table 11 it is 87.0. Are the scores based on ground-truth answer conditioning? Or In table 11 for PJ-X and FME do you take the scores for all the explanations without filtering the ones that have the wrong answer?

**Comment by maximek3** [comment]
Thanks for your question.

The difference is due to the following:

In Table 11, we compare all methods and therefore use a uniform evaluation criteria. This criteria says that we only compute the scores for the explanations where the answer was predicted correctly (described in Section 4.3). 

In Table 8, we simply want to show to what extend our re-implementations match the original performance and therefore use the evaluation criteria used in the respective papers, which may be different from the one used in Table 11. For PJ-X and FME that is conditioning the explanation generation on the ground-truth answers.

**Comment by fawazsammani** [comment]
Thanks for your answer @maximek3 
So in table 11, you mention that SE is the average explanation score for which the answer is predicted correctly. Precisely, do you mean that you average over all the portion of the scores for which the answers are predicted correctly, without setting the remaining portion for the incorrect answers to have a score of 0?

For example, let’s say you have 10 explanation, out of which 3 have a wrong associated predicted answer. Do you perform (sum_correct / 7) or (sum_correct + 0 + 0 + 0 / 10). 

I am referring to the calculation of the automatic NLG scores (B4, CiDEr, MET…etc), and not human evaluation.

**Comment by maximek3** [comment]
It's the former. So the average of all the NLG scores for explanations where the correct answer was predicted. The latter, at least for e-SNLI-VE and VCR, is equal to how we computed S_O.
